module.exports = {
  content: ["./**/*.razor"],
  theme: {
    colors: {
      "alizarin-crimson": "#e81123",
      "alto": "#e1dfdd",
      "black": "#000000",
      "cod-grey": "#1b1a19",
      "concrete": "#f3f2f1",
      "desert-storm": "#faf9f8",
      "dodger-blue": "#2899f5",
      "gallery": "#edebe9",
      "iron": "#cccccc",
      "jordy-blue": "#6cb8f6",
      "lochmara": "#0078d4",
      "masala": "#414141",
      "merlin": "#484644",
      "mine-shaft": "#292827",
      "natural-grey": "#8a8886",
      "science-blue": "#106ebe",
      "shark": "#252423",
      "solitude": "#e6f2fb",
      "star-dust": "#a19f9d",
      "storm-dust": "#646464",
      "transparent": "transparent",
      "tropical-blue": "#cce4f6",
      "tuatara": "#3b3a39",
      "venice-blue": "#005a93",
      "white": "#ffffff",
    },
    fontFamily: {
      mono: [
        "Consolas",
        '"Courier New"',
        "Courier",
        "monospace",
      ],
      sans: [
        '"Segoe UI"',
        "-apple-system",
        "BlinkMacSystemFont",
        "Roboto",
        '"Helvetica Neue"',
        "sans-serif",
      ],
    },
    fontSize: {
      "2xs": ["0.625rem", "normal"],
      "xs": ["0.6875rem", "normal"],
      "sm": ["0.75rem", "normal"],
      "base": ["0.8125rem", "normal"],
      "lg": ["0.875rem", "normal"],
      "xl": ["0.9375rem", "normal"],
      "2xl": ["1rem", "normal"],
      "3xl": ["1.0625rem", "normal"],
      "4xl": ["1.125rem", "normal"],
      "5xl": ["1.1875rem", "normal"],
      "6xl": ["1.25rem", "normal"],
    },
  },
};
