name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  create_release:
    name: Create release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
  publish_windows:
    name: Publish Windows
    needs:
      - create_release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish Windows
        run: dotnet publish --configuration "Release" --runtime "win-${{ matrix.architecture }}" --self-contained "false" ".\src\AzureAppConfigurationEmulator\AzureAppConfigurationEmulator.csproj"
      - name: Create installer
        run: . "${env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe" "/DArchitecture=${{ matrix.architecture }}" ".\setup.iss"
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/vnd.microsoft.portable-executable
          asset_name: azure-app-configuration-emulator-windows-${{ matrix.architecture }}.exe
          asset_path: .\Output\mysetup.exe
          upload_url: ${{ needs.create_release.outputs.upload_url }}
    strategy:
      matrix:
        architecture: [arm64, x64]
  push_to_registry:
    name: Push to registry
    needs:
      - create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tnc1997/azure-app-configuration-emulator
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/AzureAppConfigurationEmulator/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
